#!/usr/bin/env bash
#
# Download and install yt-dlp
#
# Usage ./yt-dlp

# Unoffical Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

curl -L https://github.com/yt-dlp/yt-dlp/releases/download/2024.11.04/yt-dlp -o $HOME/bin/yt-dlp
chmod a+rx $HOME/bin/yt-dlp
