#!/usr/bin/env bash

# Unoffical Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

# Small wrapper around git commit. Command works just like regular `git commit`
# except the commit message is prefixed with the ticket name.

ticket_name=$(ticket-name)

if [[ $# -gt 0 ]]; then
  message_lines="$*"
  title_line=$(head -1 <<< "$message_lines")
  body_lines=$(sed -e '1d' <<< "$message_lines")
  # Construct the commit message
  commit_msg=$(cat <<EOF
$title_line

[Card](https://rentpath.atlassian.net/browse/$ticket_name)

$body_lines
EOF
)

  git commit -m "$commit_msg"
else
  git commit -v
fi
