#!/bin/bash
#
# Small wrapper around git commit. Command works just like regular `git commit`
# except the commit message is prefixed with the ticket name.

# We need to include our own functions in this script in order for the
# jira_ticket command to be available
source $HOME/dotfiles/mixins/functions

ticket_name=$(ticket)

if [[ $# > 0 ]]; then
    git commit -m "$ticket_name - $@"
else
    git commit -v
fi
