#!/usr/bin/env bash

# Unoffical Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

# Small wrapper around git commit. Command works just like regular `git commit`
# except the commit message is prefixed with the ticket name.

ticket_name=$(ticket-name)

if [[ $# -gt 0 ]]; then
    git commit -m "$ticket_name - $*"
else
    git commit -v
fi
