name: Project Name
root: ~/devel/
windows:
  - main:
      layout: a353,190x47,0,0{122x47,0,0,4,67x47,123,0[67x15,123,0,5,67x15,123,16,6,67x15,123,32,7]}
      panes:
        - vim $(git status --porcelain | sed -ne 's/^ M //p')
        - # zsh
        - # zsh
        - # zsh
