#!/usr/bin/env bash

# Unoffical Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

usage() {
    cat <<EOF
    Usage: base <base> <number>
EOF
}

error_exit() {
    echo "ERROR: $1"
    usage
    exit 1
}


base=${1:-}
number=${2:-}

if [ -z $base ]; then
  error_exit "No base specified"
fi

if [ -z $number ]; then
  error_exit "No number specified"
fi

base_to_base() {
  local in=$1
  local out=$2
  local number=$3

  local result=$(echo "ibase=$in;obase=$out; $number" | bc)

  echo -e "To Base $out:\t$result"
}

#set -x
base_to_base $base 2 $number
base_to_base $base 4 $number
base_to_base $base 8 $number
base_to_base $base 10 $number
base_to_base $base 16 $number
