#!/usr/bin/env bash

# Unoffical Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

# Show color from color hex code. Useful for view CSS color codes in the terminal
#
# * https://unix.stackexchange.com/questions/482755/is-there-a-command-to-display-colors-when-giving-hex-value-in-terminal
# * https://superuser.com/questions/1713969/how-to-put-colors-in-terminal
# * https://github.com/ap/vim-css-color

# Extract 6 hexadecimal characters from hex code
color="$(echo "${1:-}" | sed 's/^#//')"

# Convert each color from hexadecimal to base 10
red="$(echo "obase=10; ibase=16; ${color:0:2}" | bc)"
green="$(echo "obase=10; ibase=16; ${color:2:2}" | bc)"
blue="$(echo "obase=10; ibase=16; ${color:4:2}" | bc)"

# Use escape codes and base10 color numbers to print block of empty space with the provided hex color
printf "\e[48;2;%s;%s;%sm     \n     \e[49m " "$red" "$green" "$blue"
