#!/usr/bin/env bash

export ASDF_NODEJS_VERSION=6.11.3

# Install it if it's not already installed
if ! hash fb-messenger-cli; then
    npm install -g fb-messenger-cli
fi

# Finally start it
fb-messenger-cli
