#!/usr/bin/env bash

# Usage -- Creates a hastebin post and prints the resulting URL:
# cat ./myFile.txt | haste

# The HASTEBIN_URL environment variable must be set in order for this script to
# work. E.g.  `export HASTEBIN_URL=https://hastebin.com`. This is done so I
# don't accidentally create hastebin snippets with company code

# Unoffical Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

if [ -z ${HASTEBIN_URL:-} ]; then
    echo "The HASTEBIN_URL environment variable must be set."
    exit 1
fi

pastebin() {
    input_string=$(cat);
    curl -X POST -s -d "$input_string" $HASTEBIN_URL/documents -v \
      | awk -v HASTEBIN_URL=$HASTEBIN_URL -F '"' '{print HASTEBIN_URL"/"$4}';
}

pastebin
