#!/usr/bin/env bash

# Unofficial Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

# Decode JWT token passed via STDIN

jq -R 'split(".") |.[0:2] | map(@base64d) | map(fromjson)'
