#!/usr/bin/env bash

# Unoffical Bash "strict mode"
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
#ORIGINAL_IFS=$IFS
IFS=$'\t\n' # Stricter IFS settings

# TODO: Consider removing this script entirely. It's not something I often use

uppercase_branch_name() {
    # Get the branch name
    BRANCH_NAME="$(git branch-name)";

    # Make branch name uppercase (JIRA tickets are uppercase)
    UPPERCASE_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:lower:]' '[:upper:]');

    # Echo branch name
    echo "$UPPERCASE_BRANCH_NAME";
}

jira_ticket() {
    # Get the uppercase branch name
    branch_name="$(uppercase_branch_name)"

    # Remove everything before the slash and after the numbers. For example,
    # `feat/abc-123-something-something` becomes `abc-123`
    jira_ticket_name="$(echo "$branch_name" | cut -f2 -d/ | sed 's/\(^[[:alpha:]]*-[0-9]*\)\(.*\)/\1/g')"

    echo "$jira_ticket_name"
}

jira_ticket
