= Recording the Terminal

== Recording

=== Setup a tmux Session Optimized for Recording

[source, sh]
----
# Create new tmux session for recording
$ tmux new-session -s recording-studio

# Run the resize-window command to set tmux window to good size for recording
:resize-window -y 24 -x 80
----

TODO: Figure out best prompt for recording.

=== Generate the Recording

We can record a terminal session directory with Asciinema. However, as detailed link:https://effective-shell.com/zz-developer-guide/recording-terminal-sessions/[here] it can be helpful to discard timing information if your typing is inconsistent or you need to pause and look something up during recording. link:https://github.com/scoopex/scriptreplay_ng[scriptreplay_ng] is the only tool I've found that allows you to discard timing information. This makes each keystroke appear at a consistent interval and makes for a more polished presentation.

Steps:

1. Install scriptreplay_ng if you haven't already link:[install script]
2. Record the session:

[source, sh]
----
$ record-script-session <session name>

# Do what you want to record
$ ...
# Ctrl-D to exit
----

=== Convert the Recording to Asciinema format

Inside the tmux session configured for terminal record, begin the recording:

[source, sh]
----
asciinema rec --command "scriptreplay-ng recording.txt"
----

== Converting to an Animated GIF

Sometimes it's necessary to convert the terminal record into a format that can be viewed anywhere.

The asciinema `agg` tool converts asciinema recordings into animated GIFs. The generated GIF file
can then be converted to another format like MP4.

Steps:

1. Install link:https://github.com/asciinema/agg[asciinema/agg].
2. Run `agg <ASCIINEMA FILE> <OUTPUT GIF FILE>` with any options you want.

=== Converting the GIF to an MP4 Video

Steps:

1. Install `ffmpeg` if you don't already have it installed.
2. Run `ffmpeg -i <GIF FILE> -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" <OUTPUT MP4 FILE>`

== References

* https://effective-shell.com/zz-developer-guide/recording-terminal-sessions
* https://unix.stackexchange.com/questions/250183/using-scriptreplay-without-timing-file
* https://github.com/Malinskiy/spielbash
* https://graphicdesign.stackexchange.com/questions/104535/delay-playing-animated-gif-in-powerpoint
* https://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line
